### ISSUE TITLE
warning: no river type provided for [_river], ignoring...

### ISSUE THREAD

**Issue by bsll** [elasticsearch/elasticsearch-river-rabbitmq#87]
Hi,when I try the plugin in my ES,I get  the feedback......
[2015-01-13 21:48:58,583][WARN ][river.routing            ] [test_node1] no river type provided for [_river], ignoring...
is it because that the data in rabbitmq's queue isn't the bulk format ? I am sure it is the JSON format.

**Comment by dadoonet** [comment]
Sorry. We can not understand without knowing details about what you tried so far.
Please first read the [README](https://github.com/elasticsearch/elasticsearch-river-rabbitmq/blob/master/README.md).

Closing as it's not an issue. Feel free to update this thread with details or ask this on the mailing list.

**Comment by bsll** [comment]
I have the setting.
{
    "type" : "rabbitmq",
    "dynamic":true,
    "rabbitmq" : {
        "host" : "192.168.1.214",
        "port" : 5672,
        "user" : "guest",
        "pass" : "guest",
        "vhost" : "/",
        "queue" : "essay_anly_copy_v3",
        "exchange" : "essay_anly",
        "routing_key" : "",
        "exchange_declare" : true,
        "exchange_type" : "fanout",
        "exchange_durable" : true,
        "queue_declare" : true,
        "queue_bind" : false,
        "queue_durable" : true,
        "queue_auto_delete" : false,
        "heartbeat" : "1m",
        "qos_prefetch_size" : 0,
        "qos_prefetch_count" : 10,
        "nack_errors" : true
    },
    "index" : {
        "bulk_size" : 100,
        "bulk_timeout" : "10ms",
        "ordered" : false,
        "replication" : "default"
    }
}
and I don't know why get the feedback about "no _river type". I guess it may be related to the data format.
Before  the data is put into the rabbitmq, I must translate the data format  into the bulk format, or the plugin do this partwork   ? I just want to  confirm this point.
‍





------------------ 原始邮件 ------------------
发件人: "David Pilato";<notifications@github.com>;
发送时间: 2015年1月13日(星期二) 晚上10:28
收件人: "elasticsearch/elasticsearch-river-rabbitmq"<elasticsearch-river-rabbitmq@noreply.github.com>; 
抄送: "小小了了"<928190906@qq.com>; 
主题: Re: [elasticsearch-river-rabbitmq] warning: no river type providedfor [_river], ignoring... (#87)




Closed #87.

**Comment by dadoonet** [comment]
Well I guess it depends on how you send this to elasticsearch.

**Comment by bsll** [comment]
? Sorry, I don't understand your words. So Why I get the feedback like "no type _river..."?




------------------ 原始邮件 ------------------
发件人: "David Pilato";<notifications@github.com>;
发送时间: 2015年1月13日(星期二) 晚上11:00
收件人: "elasticsearch/elasticsearch-river-rabbitmq"<elasticsearch-river-rabbitmq@noreply.github.com>; 
抄送: "小小了了"<928190906@qq.com>; 
主题: Re: [elasticsearch-river-rabbitmq] warning: no river type providedfor [_river], ignoring... (#87)




Well I guess it depends on how you send this to elasticsearch.

**Comment by dadoonet** [comment]
What exact command do you use to create the river?

**Comment by bsll** [comment]
curl -XPUT 'localhost:9200/_river/my_river/_meta' -d '{     "type" : "rabbitmq",     "rabbitmq" : {.....     },     "index" : {.....     } }
As the format,, I exchange the 'my_river' into another name.‍
and I get the feedback.
{
   "_index": "_river",
   "_type": "my_river",
   "_id": "_meta",
   "_version": 1,
   "created": true
}‍




------------------ 原始邮件 ------------------
发件人: "David Pilato";<notifications@github.com>;
发送时间: 2015年1月13日(星期二) 晚上11:32
收件人: "elasticsearch/elasticsearch-river-rabbitmq"<elasticsearch-river-rabbitmq@noreply.github.com>; 
抄送: "小小了了"<928190906@qq.com>; 
主题: Re: [elasticsearch-river-rabbitmq] warning: no river type providedfor [_river], ignoring... (#87)



What exact command do you use to create the river?

**Comment by dadoonet** [comment]
So? Is it working now?

**Comment by bsll** [comment]
NO, and I can't find any messages about the rabbitmq from elasticsearch.log.‍


------------------ 原始邮件 ------------------
发件人: "David Pilato";<notifications@github.com>;
发送时间: 2015年1月14日(星期三) 中午12:08
收件人: "elasticsearch/elasticsearch-river-rabbitmq"<elasticsearch-river-rabbitmq@noreply.github.com>; 
抄送: "小小了了"<928190906@qq.com>; 
主题: Re: [elasticsearch-river-rabbitmq] warning: no river type providedfor [_river], ignoring... (#87)




So? Is it working now?

**Comment by dadoonet** [comment]
So where the initial log you pasted come from?

**Comment by bsll** [comment]
The path :elasticsearch/logs/elasticsearch.log   ‍




------------------ 原始邮件 ------------------
发件人: "David Pilato";<notifications@github.com>;
发送时间: 2015年1月14日(星期三) 下午4:44
收件人: "elasticsearch/elasticsearch-river-rabbitmq"<elasticsearch-river-rabbitmq@noreply.github.com>; 
抄送: "小小了了"<928190906@qq.com>; 
主题: Re: [elasticsearch-river-rabbitmq] warning: no river type providedfor [_river], ignoring... (#87)




So where the initial log you pasted come from?

**Comment by dadoonet** [comment]
Could you please:
Repeat all Steps from the begining
Paste here all commands you ran
Paste your full logs

Thanks

**Comment by bsll** [comment]
Sorry,I have some other urgent things to do now.I will send you later.‍



------------------ 原始邮件 ------------------
发件人: "David Pilato";<notifications@github.com>;
发送时间: 2015年1月14日(星期三) 下午5:44
收件人: "elasticsearch/elasticsearch-river-rabbitmq"<elasticsearch-river-rabbitmq@noreply.github.com>; 
抄送: "小小了了"<928190906@qq.com>; 
主题: Re: [elasticsearch-river-rabbitmq] warning: no river type providedfor [_river], ignoring... (#87)




Could you please:
 Repeat all Steps from the begining
 Paste here all commands you ran
 Paste your full logs
 
Thanks

**Comment by bsll** [comment]
I'm very sorry to reply you so later.
I have fix the problem. It's that I ever installed the couchbase_to_elasticsearch plugin before I install the plugin.When I delete the old Plugin, It works.
Thank you!
 ‍



------------------ 原始邮件 ------------------
发件人: "David Pilato";<notifications@github.com>;
发送时间: 2015年1月14日(星期三) 下午5:44
收件人: "elasticsearch/elasticsearch-river-rabbitmq"<elasticsearch-river-rabbitmq@noreply.github.com>; 
抄送: "小小了了"<928190906@qq.com>; 
主题: Re: [elasticsearch-river-rabbitmq] warning: no river type providedfor [_river], ignoring... (#87)




Could you please:
 Repeat all Steps from the begining
 Paste here all commands you ran
 Paste your full logs
 
Thanks
