### ISSUE TITLE
Selective nacking of failed items within the bulk (in order to route only failed messages to a deadletter queue).

### ISSUE THREAD

**Issue by aznamier** [elasticsearch/elasticsearch-river-rabbitmq#88]
We possibly need a solution to selectively nack messages within a bulk request. Then it will be possible to simply setup a deadletter routing and have only the failed messages within a bulk landing in the "error" queue.

Thats how I added a deadletter to a river:

```javascript
	...
    "rabbitmq" : {
    	 ...
	      "nack_errors" : true,
	      "args" :  {
	        "x-dead-letter-exchange":"system.error",
	        "x-dead-letter-routing-key":"ES.rcv.error" 
	      }
    },
    "index" : {
    	...
    }
```
And i have done code changes to support selective nacking. 
Is anybody working on this? Or should i create a pull request.

**Comment by dadoonet** [comment]
My advice would be to contribute that kind of feature in logstash project as rivers will be most likely deprecated in the future.

**Comment by nhooey** [comment]
What would rivers be replaced with in the future?

**Comment by dadoonet** [comment]
logstash is acting as a river (with more power and flexibility) but runs externally to elasticsearch nodes which is definitely a better option.

**Comment by aznamier** [comment]
You are absolutely right. I will check with the logstash project. But does that mean no more development to this project?

**Comment by dadoonet** [comment]
@aznamier We will most likely fix issues. Not sure we will add new features in it.
